package de.dfki.opends.gauge.util;

public enum ViewMappings {
    LEFT_TURN,
    RIGHT_TURN,
    HANDBRAKE,
    SPEEDOMETER,
    SPEEDOMETER_DIGITAL,
    RPM_METER,
    CURRENT_GEAR,
    CURRENT_SHIFT,
    NAVIGATION,
    FUEL_METER,
    HEAD_LIGHTS,
    FUEL_LIGHTS,
    TYRE_PRESSURE_LIGHTS,
    CRUISE_CONTROL_LIGHTS,
    FROST_LIGHTS,
    CHECK_ENGINE_LIGHTS,
    OIL_LIGHTS,
    SEAT_BELT_LIGHTS,
    BATTERY_LIGHTS;
}
